// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKFU6pKmSQJVjOXYjdWHegpExc4yAINzU',
    appId: '1:1074826500230:web:f1400c840a659d0d239907',
    messagingSenderId: '1074826500230',
    projectId: 'activity17-8edc9',
    authDomain: 'activity17-8edc9.firebaseapp.com',
    storageBucket: 'activity17-8edc9.firebasestorage.app',
    measurementId: 'G-Z4JPVZ8NFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQMAeEA9uR0PU5--SVVLpJ6tIs6R2R0M',
    appId: '1:1074826500230:android:cbe421376e8994d6239907',
    messagingSenderId: '1074826500230',
    projectId: 'activity17-8edc9',
    storageBucket: 'activity17-8edc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSu1rAym65eBzBio4W2GAD8UR3UYjZJJ0',
    appId: '1:1074826500230:ios:23044a4cc324b12c239907',
    messagingSenderId: '1074826500230',
    projectId: 'activity17-8edc9',
    storageBucket: 'activity17-8edc9.firebasestorage.app',
    iosBundleId: 'com.example.ac17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSu1rAym65eBzBio4W2GAD8UR3UYjZJJ0',
    appId: '1:1074826500230:ios:23044a4cc324b12c239907',
    messagingSenderId: '1074826500230',
    projectId: 'activity17-8edc9',
    storageBucket: 'activity17-8edc9.firebasestorage.app',
    iosBundleId: 'com.example.ac17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKFU6pKmSQJVjOXYjdWHegpExc4yAINzU',
    appId: '1:1074826500230:web:c5cc6801a1a51d63239907',
    messagingSenderId: '1074826500230',
    projectId: 'activity17-8edc9',
    authDomain: 'activity17-8edc9.firebaseapp.com',
    storageBucket: 'activity17-8edc9.firebasestorage.app',
    measurementId: 'G-1F5R5XFFRQ',
  );
}
